### ISSUE TITLE
Need Reference BDT feats lists/table

### ISSUE THREAD

**Issue by juan-mlr** [juan-mlr/ecal-bdt#11]
![image](https://user-images.githubusercontent.com/48661362/115976055-fac8d600-a51e-11eb-929c-a7200daea05d.png)

**Comment by juan-mlr** [comment]
Adressed with commit 90ba4e46b11dcf197bbf059dc49a2f1805cc38ed

**Comment by aechavez** [comment]
Here's a rough draft of the feature doc. Let me know what you think
[features.txt](https://github.com/jmlazaro25/bdt/files/6373010/features.txt)
