### ISSUE TITLE
Numpy Warning slowing things down significantly

### ISSUE THREAD

**Issue by juan-mlr** [juan-mlr/ecal-bdt#5]
I get this when I import one of your mods (not sure which one, I just imported them all). It looks like something that you could fix just by building an array in a different way. Also, if it has anything to do with the z positions (haven't looked into it), maybe just don't since they're in physTools.

> master | bdt $ ldmx python3 treeMaker.py --interactive -i $PWD/samples_2.3.0/4gev_v12_map_0.01_15_ldmx-det-v12_run25_seeds_50_51_0.01.root -g 0.01 --out $PWD/flats -m 1
> /home/jmlazaro/research/bdt/mods/ecalHexReadoutTools.py:269: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray

**Comment by aechavez** [comment]
The change that I just pushed to my branch should get rid of this warning. Since the base variables are pre-computed, I removed large chunks of code from my mods that we won't be needing. This should speed things up significantly, and also has the added benefit of removing that warning.
